### ISSUE TITLE
404 Page on Hide Quotes

### ISSUE THREAD

**Issue by eyang1608** [epiccakeking/aops-enhanced#22]
**Describe the bug**
Changing quote setting to "Hide" and then posting, then clicking the username under the hide tag results in a broken link (404). 

**To Reproduce**
1. Set your quote setting to "Hide". 
2. Post with a quote.
3. Click on the hide tag.
4. Click on the username.
5. 404 page.

**Expected behavior**
Link should bring to user's profile page. 

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Microsoft Edge]
 - Version [e.g. 92]

**Comment by eyang1608** [comment]
The current link follows the format https://artofproblemsolving.com/user/[6-digit number I'm not sure the name of]

While the correct link should be https://artofproblemsolving.com/community/user/[6-digit number I'm not sure the name of]

To be honest should be a simple fix.

**Comment by epiccakeking** [comment]
This should now be fixed in the 6-devel branch
